### ISSUE TITLE
Search for filename instead of repo topic

### ISSUE THREAD

**Issue by nicolas-martin** [Kharacternyk/dotcommon#1]
https://github.com/Kharacternyk/dotcommon/blob/374424d5e1160d98b4d9552eece2834eddd9e2ab/src/dotcommon/crawl.py#L12

As per the [search documentation](https://help.github.com/en/github/searching-for-information-on-github/searching-code#search-by-filename) by using code search instead of repo search you can do  `filename:.vimrc`.

**Comment by Kharacternyk** [comment]
Thanks!
