### ISSUE TITLE
Count custom functions in vimrc

### ISSUE THREAD

**Issue by weirdsmiley** [Kharacternyk/dotcommon#10]
I saw a post on Reddit (perhaps) where the author crawled how many custom functions people, on average, are having in their vimrcs. I think that would be a cool stat. to have. It may also push Vim users to use Vimscript more often and define functions according to their needs.

**Comment by Kharacternyk** [comment]
I am not sure, but I vaguely remember that this stat was here but was then removed. Need to check the git history. Anyway, I don't think I'll come back to writing code for dotcommon anytime soon. PRs are welcome, though.
