### ISSUE TITLE
Search for config files in subdirectories

### ISSUE THREAD

**Issue by BertalanD** [Kharacternyk/dotcommon#11]
Using [GNU stow](https://www.gnu.org/software/stow/) is a somewhat common way for managing dotfiles in a modular way, as used by [me](https://github.com/BertalanD/dotfiles). This usually means that for each application, a separate directory is created, and their contents get symlinked to the root directory.

One solution is to look for the files of interest recursively, or at least in the first level subdirctories. I suppose we could also grep each file and attempt to classify whether an alias is used in zsh or bash based on filename.

**Comment by Kharacternyk** [comment]
I've accidentally replied to both of your issues at once in #12.
