### ISSUE TITLE
No such file or directory: 'token.gh'

### ISSUE THREAD

**Issue by salil-sudo** [Kharacternyk/dotcommon#13]
Not sure if I am using the scripts correctly, but when I run `bspwm.py` it gives me the error :`FileNotFoundError: [Errno 2] No such file or directory: 'token.gh'`. Also, what is the proper way to run your scripts ?

**Comment by Kharacternyk** [comment]
The `token.gh` is a file that contains a GitHub API token. The token is required to programmatically interact with GitHub and can be generated in the GitHub account settings.

But you probably don't need to run the scripts, though. The idea was that ***I*** would periodically run `update.sh` (it's in the project root), which would run the python scripts that fetch the data from GitHub, generate the new README, and commit it. I then lost interest in the project, and the data hasn't been updated for a long time.

**Comment by salil-sudo** [comment]
Thanks for the update. The reason I wanted to use was to go through the shell scripts people use and run `shellcheck` on them to see the top 5-10 most common instances of improper scripting. Do you think it is possible to do if its no too much work for you ? Or if I can do that by myself ?

**Comment by Kharacternyk** [comment]
So you want to run shellcheck on scripts in repos on GitHub, right? That's interesting, but dotcommon can only look for scripts based on their filenames. That restricts such idea, doesn't it?

**Comment by salil-sudo** [comment]
Ah. My idea was to look for strings such as "`#!/bin/sh` or `#!/bin/bash`. But if your scripts look for file names, that might be tough. Maybe the the script can look for for file names with "*.sh" or use some regex on file contents. Do you think thats possible ?

**Comment by Kharacternyk** [comment]
Yes, it is possible to query files by extension.

**Comment by salil-sudo** [comment]
So, I see from the scripts, it looks for instances of strings given a file name and atomizers. But I want to have entire file and run the command `shellcheck` on it and save top 5-10 outputs I get. Any pointers on how to proceed with this ?

**Comment by Kharacternyk** [comment]
To be honest, I believe that you won't make good use of dotcommon for your project. I would suggest you to see the docs of PyGitHub and build a crawler yourself. Dotcommon doesn't do anything particularly complex with the GitHub API, so writing something from scratch while looking at dotcommon as an example would be the right thing to do, in my opinion. Also, you should remember that GitHub limits API requests to something like 3000 per day, so don't be afraid when something suddenly stops working, you probably just need to wait in such case.
