### ISSUE TITLE
Add zsh

### ISSUE THREAD

**Issue by worldpotato** [Kharacternyk/dotcommon#4]
add crawling for zsh configs.
Because zsh is often used by people who customize their linux.

**Comment by Kharacternyk** [comment]
Zsh is must have, but I'm not familiar with it at all. It has like 3 configs for various things, isn't it? I would like contributors to write presets for apps they use, it should be quite easy.

**Comment by worldpotato** [comment]
Well, it has `~/.zshrc` as the main config file. Then the `~/.zprofile` as replacement for the `~/.bash_profile` file.
And is has the theme files. But these should only contain the $PS1 and is not so interesting for me.

I think will give it a shot.
